foTeam = {
    '2TM' : '2TM',
    'ARI' : 'ARI',
    'ATL' : 'ATL',
    'BAL' : 'BAL',
    'BUF' : 'BUF',
    'CAR' : 'CAR',
    'CHI' : 'CHI',
    'CIN' : 'CIN',
    'CLE' : 'CLE',
    'DAL' : 'DAL',
    'DEN' : 'DEN',
    'DET' : 'DET',
    'GB' : 'GB',
    'HOU' : 'HOU',
    'IND' : 'IND',
    'JAC' : 'JAC',
    'KC' : 'KC',
    'LACH' : 'LAC',
    'LARM' : 'LAR',
    'MIA' : 'MIA',
    'MIN' : 'MIN',
    'NE' : 'NE',
    'NO' : 'NO',
    'NYG' : 'NYG',
    'NYJ' : 'NYJ',
    'OAK' : 'OAK',
    'PHI' : 'PHI',
    'PIT' : 'PIT',
    'SD' : 'SD',
    'SEA' : 'SEA',
    'SF' : 'SF',
    'STL' : 'STL',
    'TB' : 'TB',
    'TEN' : 'TEN',
    'WAS' : 'WAS',
    'LV' : 'LV',
    'LVR' : 'LV',
    '' : 'none'
    }

ffTeam = {
    'ARI' : 'ARI',
    'ATL' : 'ATL',
    'BAL' : 'BAL',
    'BUF' : 'BUF',
    'CAR' : 'CAR',
    'CHI' : 'CHI',
    'CIN' : 'CIN',
    'CLE' : 'CLE',
    'DAL' : 'DAL',
    'DEN' : 'DEN',
    'DET' : 'DET',
    'GB' : 'GB',
    'HOU' : 'HOU',
    'IND' : 'IND',
    'JAC' : 'JAC',
    'KC' : 'KC',
    'LAC' : 'LAC',
    'LAR' : 'LAR',
    'MIA' : 'MIA',
    'MIN' : 'MIN',
    'NE' : 'NE',
    'NO' : 'NO',
    'NYG' : 'NYG',
    'NYJ' : 'NYJ',
    'OAK' : 'OAK',
    'PHI' : 'PHI',
    'PIT' : 'PIT',
    'SD' : 'SD',
    'SEA' : 'SEA',
    'SF' : 'SF',
    'STL' : 'STL',
    'TB' : 'TB',
    'TEN' : 'TEN',
    'WAS' : 'WAS',
    'LV' : 'LV',
    'LVR' : 'LV',
    '' : 'none'
    }

fullName = {
    'Arizona Cardinals' : 'ARI',
    'Atlanta Falcons' : 'ATL',
    'Baltimore Ravens' : 'BAL',
    'Buffalo Bills' : 'BUF',
    'Carolina Panthers' : 'CAR',
    'Chicago Bears' : 'CHI',
    'Cincinnati Bengals' : 'CIN',
    'Cleveland Browns' : 'CLE',
    'Dallas Cowboys' : 'DAL',
    'Denver Broncos' : 'DEN',
    'Detroit Lions' : 'DET',
    'Green Bay Packers' : 'GB',
    'Houston Texans' : 'HOU',
    'Indianapolis Colts' : 'IND',
    'Jacksonville Jaguars' : 'JAC',
    'Kansas City Chiefs' : 'KC',
    'Los Angeles Chargers' : 'LAC',
    'Los Angeles Rams' : 'LAR',
    'Miami Dolphins' : 'MIA',
    'Minnesota Vikings' : 'MIN',
    'New England Patriots' : 'NE',
    'New Orleans Saints' : 'NO',
    'New York Giants' : 'NYG',
    'New York Jets' : 'NYJ',
    'Oakland Raiders' : 'OAK',
    'Philadelphia Eagles' : 'PHI',
    'Pittsburgh Steelers' : 'PIT',
    'San Diego Chargers' : 'SD',
    'San Francisco 49ers' : 'SF',
    'Seattle Seahawks' : 'SEA',
    'St. Louis Rams' : 'STL',
    'Tampa Bay Buccaneers' : 'TB',
    'Tennessee Titans' : 'TEN',
    'Washington Redskins' : 'WAS',
    'Las Vegas Raiders' : 'LV',
    'Washington Football Team' : 'WAS',
    '' : 'none'
    }

fullNameUCase = {
    'ARIZONA CARDINALS' : 'ARI',
    'ATLANTA FALCONS' : 'ATL',
    'BALTIMORE RAVENS' : 'BAL',
    'BUFFALO BILLS' : 'BUF',
    'CAROLINA PANTHERS' : 'CAR',
    'CHICAGO BEARS' : 'CHI',
    'CINCINNATI BENGALS' : 'CIN',
    'CLEVELAND BROWNS' : 'CLE',
    'DALLAS COWBOYS' : 'DAL',
    'DENVER BRONCOS' : 'DEN',
    'DETROIT LIONS' : 'DET',
    'GREEN BAY PACKERS' : 'GB',
    'HOUSTON TEXANS' : 'HOU',
    'INDIANAPOLIS COLTS' : 'IND',
    'JACKSONVILLE JAGUARS' : 'JAC',
    'KANSAS CITY CHIEFS' : 'KC',
    'LOS ANGELES CHARGERS' : 'LAC',
    'LOS ANGELES RAMS' : 'LAR',
    'MIAMI DOLPHINS' : 'MIA',
    'MINNESOTA VIKINGS' : 'MIN',
    'NEW ENGLAND PATRIOTS' : 'NE',
    'NEW ORLEANS SAINTS' : 'NO',
    'NEW YORK GIANTS' : 'NYG',
    'NEW YORK JETS' : 'NYJ',
    'OAKLAND RAIDERS' : 'OAK',
    'PHILADELPHIA EAGLES' : 'PHI',
    'PITTSBURGH STEELERS' : 'PIT',
    'SAN DIEGO CHARGERS' : 'SD',
    'SAN FRANCISCO 49ERS' : 'SF',
    'SEATTLE SEAHAWKS' : 'SEA',
    'ST. LOUIS RAMS' : 'STL',
    'TAMPA BAY BUCCANEERS' : 'TB',
    'TENNESSEE TITANS' : 'TEN',
    'WASHINGTON REDSKINS' : 'WAS',
    'LAS VEGAS RAIDERS' : 'LV',
    'WASHINGTON FOOTBALL TEAM' : 'WAS',
    '' : 'none'

    }


teamLocation = {
    'Arizona' : 'ARI',
    'Atlanta' : 'ATL',
    'Baltimore' : 'BAL',
    'Buffalo' : 'BUF',
    'Carolina' : 'CAR',
    'Chicago' : 'CHI',
    'Cincinnati' : 'CIN',
    'Cleveland' : 'CLE',
    'Dallas' : 'DAL',
    'Denver' : 'DEN',
    'Detroit' : 'DET',
    'Green Bay' : 'GB',
    'Houston' : 'HOU',
    'Indianapolis' : 'IND',
    'Jacksonville' : 'JAC',
    'Kansas City' : 'KC',
    'Los Angeles Chargers' : 'LAC',
    'Los Angeles Rams' : 'LAR',
    'Los Angeles' : 'LAR',
    'Miami' : 'MIA',
    'Minnesota' : 'MIN',
    'New England' : 'NE',
    'New Orleans' : 'NO',
    'New York' : 'NYG',
    'New York Giants' : 'NYG',
    'New York Jets' : 'NYJ',
    'Oakland' : 'OAK',
    'Philadelphia' : 'PHI',
    'Pittsburgh' : 'PIT',
    'San Diego' : 'SD',
    'San Francisco' : 'SF',
    'Seattle' : 'SEA',
    'St. Louis' : 'STL',
    'Tampa Bay' : 'TB',
    'Tennessee' : 'TEN',
    'Washington' : 'WAS',
    'Las Vegas' : 'LV',
    '' : 'none'
    }

pfrAbbrName = {
    'ARI' : 'ARI',
    'ATL' : 'ATL',
    'BAL' : 'BAL',
    'BUF' : 'BUF',
    'CAR' : 'CAR',
    'CHI' : 'CHI',
    'CIN' : 'CIN',
    'CLE' : 'CLE',
    'DAL' : 'DAL',
    'DEN' : 'DEN',
    'DET' : 'DET',
    'GNB' : 'GB',
    'HOU' : 'HOU',
    'IND' : 'IND',
    'JAX' : 'JAC',
    'KAN' : 'KC',
    'LAC' : 'LAC',
    'LAR' : 'LAR',
    'MIA' : 'MIA',
    'MIN' : 'MIN',
    'NOR' : 'NO',
    'NWE' : 'NE',
    'NYG' : 'NYG',
    'NYJ' : 'NYJ',
    'OAK' : 'OAK',
    'PHI' : 'PHI',
    'PIT' : 'PIT',
    'SDG' : 'SD',
    'SEA' : 'SEA',
    'SFO' : 'SF',
    'STL' : 'STL',
    'TAM' : 'TB',
    'TEN' : 'TEN',
    'WAS' : 'WAS',
    'LV' : 'LV',
    'LVR' : 'LV',
    '' : 'none'
    }

laligaName = {
    'Ari' : 'ARI',
    'Atl' : 'ATL',
    'Bal' : 'BAL',
    'Buf' : 'BUF',
    'Car' : 'CAR',
    'Chi' : 'CHI',
    'Cin' : 'CIN',
    'Cle' : 'CLE',
    'Dal' : 'DAL',
    'Den' : 'DEN',
    'Det' : 'DET',
    'FA' : 'none',
    'GB' : 'GB',
    'Hou' : 'HOU',
    'Ind' : 'IND',
    'Jac' : 'JAC',
    'Jax' : 'JAC',
    'KC' : 'KC',
    'LAC' : 'LAC',
    'LAR' : 'LAR',
    'Mia' : 'MIA',
    'Min' : 'MIN',
    'NE' : 'NE',
    'NO' : 'NO',
    'NYG' : 'NYG',
    'NYJ' : 'NYJ',
    'Oak' : 'OAK',
    'Phi' : 'PHI',
    'Pit' : 'PIT',
    'SD' : 'SD',
    'Sea' : 'SEA',
    'SF' : 'SF',
    'StL' : 'STL',
    'TB' : 'TB',
    'Ten' : 'TEN',
    'Was' : 'WAS',
    'Wsh' : 'WAS',
    '' : 'none',
    'LA' : 'LAR',
    'LV' : 'LV',
    'LVR' : 'LV',
    }

fullToMascot = {
    'Arizona Cardinals' : 'Cardinals',
    'Atlanta Falcons' : 'Falcons',
    'Baltimore Ravens' : 'Ravens',
    'Buffalo Bills' : 'Bills',
    'Carolina Panthers' : 'Panthers',
    'Chicago Bears' : 'Bears',
    'Cincinnati Bengals' : 'Bengals',
    'Cleveland Browns' : 'Browns',
    'Dallas Cowboys' : 'Cowboys',
    'Denver Broncos' : 'Broncos',
    'Detroit Lions' : 'Lions',
    'Green Bay Packers' : 'Packers',
    'Houston Texans' : 'Texans',
    'Indianapolis Colts' : 'Colts',
    'Jacksonville Jaguars' : 'Jaguars',
    'Kansas City Chiefs' : 'Chiefs',
    'Los Angeles Chargers' : 'Chargers',
    'Los Angeles Rams' : 'Rams',
    'Miami Dolphins' : 'Dolphins',
    'Minnesota Vikings' : 'Vikings',
    'New England Patriots' : 'Patriots',
    'New Orleans Saints' : 'Saints',
    'New York Giants' : 'Giants',
    'New York Jets' : 'Jets',
    'Oakland Raiders' : 'Raiders',
    'Philadelphia Eagles' : 'Eagles',
    'Pittsburgh Steelers' : 'Steelers',
    'San Diego Chargers' : 'Chargers',
    'San Francisco 49ers' : '49ers',
    'Seattle Seahawks' : 'Seahawks',
    'St. Louis Rams' : 'Rams',
    'Tampa Bay Buccaneers' : 'Buccaneers',
    'Tennessee Titans' : 'Titans',
    'Washington Redskins' : 'Redskins',
    'Washington Football Team' : 'Washington',
    '' : 'none'
    }

abbrToMascot = {
    'ARI' : 'Cardinals',
    'ATL' : 'Falcons',
    'BAL' : 'Ravens',
    'BUF' : 'Bills',
    'CAR' : 'Panthers',
    'CHI' : 'Bears',
    'CIN' : 'Bengals',
    'CLE' : 'Browns',
    'DAL' : 'Cowboys',
    'DEN' : 'Broncos',
    'DET' : 'Lions',
    'GB' : 'Packers',
    'HOU' : 'Texans',
    'IND' : 'Colts',
    'JAC' : 'Jaguars',
    'KC' : 'Chiefs',
    'LAC' : 'Chargers',
    'LAR' : 'Rams',
    'MIA' : 'Dolphins',
    'MIN' : 'Vikings',
    'NE' : 'Patriots',
    'NO' : 'Saints',
    'NYG' : 'Giants',
    'NYJ' : 'Jets',
    'OAK' : 'Raiders',
    'PHI' : 'Eagles',
    'PIT' : 'Steelers',
    'SD' : 'Chargers',
    'SEA' : 'Seahawks',
    'SF' : '49ers',
    'STL' : 'Rams',
    'TB' : 'Buccaneers',
    'TEN' : 'Titans',
    'WAS' : 'Washington',
    'LV' : 'Raiders',
    'LVR' : 'Raiders',
    '' : 'none'
    }

errorSQL = ("insert into scrapped_data.errorLog" +
            "(pythonError, sqlScript, runDateTime) " +
            "values ('%s', '%s', current_timestamp());")



statDict = {1 : '',
            2 : 'Passing Attempts',
            3 : 'Completions',
            4 : 'Incompletions',
            5 : 'Passing Yards',
            6 : 'Passing TD',
            7 : 'Interceptions Thrown',
            8 : 'QB Sacks',
            9 : '300-399 Passing Yards Bonus',
            10 : '400+ Passing Yards Bonus',
            11 : '40+ Passing Yard TD Bonus',
            12 : '50+ Passing Yards TD Bonus',
            13 : 'Rushing Attempts',
            14 : 'Rushing Yards',
            15 : 'Rushing Touchdowns',
            16 : '40+ Rushing Yard TD Bonus',
            17 : '50+ Rushing Yard TD Bonus',
            18 : '100-199 Rushing Yards Bonus',
            19 : '200+ Rushing Yards Bonus',
            20 : 'Receptions',
            21 : 'Receiving Yards',
            22 : 'Receiving Touchdowns',
            23 : '40+ Receiving Yard TD Bonus',
            24 : '50+ Receiving Yard TD Bonus',
            25 : '100-199 Receiving Yards Bonus',
            26 : '200+ Receiving Yards Bonus',
            27 : 'Kickoff and Punt Return Yards',
            28 : 'Kickoff and Punt Return Touchdowns',
            29 : 'Fumble Recovered for TD',
            30 : 'Fumbles Lost',
            31 : 'Fumble',
            32 : '2-Point Conversions',
            33 : 'PAT Made',
            34 : 'PAT Missed',
            35 : 'FG Made 0-19',
            36 : 'FG Made 20-29',
            37 : 'FG Made 30-39',
            38 : 'FG Made 40-49',
            39 : 'FG Made 50+',
            40 : 'FG Missed 0-19',
            41 : 'FG Missed 20-29',
            42 : 'FG Missed 30-39',
            43 : 'FG Missed 40-49',
            44 : 'FG Missed 50+',
            45 : 'Sacks',
            46 : 'Interceptions',
            47 : 'Fumbles Recovered',
            48 : 'Fumbles Forced',
            49 : 'Safeties',
            50 : 'Defensive Touchdowns',
            51 : 'Blocked Kicks',
            52 : 'Kickoff and Punt Return Yards',
            53 : 'Kickoff and Punt Return Touchdowns',
            54 : 'Points Allowed',
            55 : 'Points Allowed 0',
            56 : 'Points Allowed 1-6',
            57 : 'Points Allowed 7-13',
            58 : 'Points Allowed 14-20',
            59 : 'Points Allowed 21-27',
            60 : 'Points Allowed 28-34',
            61 : 'Points Allowed 35+',
            62 : 'Yards Allowed',
            63 : 'Less than 100 Total Yards Allowed',
            64 : '100-199 Yards Allowed',
            65 : '200-299 Yards Allowed',
            66 : '300-399 Yards Allowed',
            67 : '400-449 yards Allowed',
            68 : '450-499 Yards Allowed',
            69 : '500+Yards Allowed',
            70 : 'Tackle',
            71 : 'Assisted Tackles',
            72 : 'Sacks',
            73 : 'Defensive Interception',
            74 : 'Forced Fumble',
            75 : 'Fumbles Recovery',
            76 : 'INT Touchdown',
            77 : 'Fumble Touchdown',
            78 : 'Blocked Kick Touchdown',
            79 : 'Safety',
            80 : 'Pass Defended',
            81 : 'INT Return Yards',
            82 : 'Fumble Return Yards',
            83 : 'Tackles for Loss',
            84 : 'QB Hit',
            85 : 'Sack yards',
            86 : '10+ Tackle Bonus',
            87 : '2+ Sack Bonus',
            88 : '3+ Passes Defended Bonus',
            89 : '50+ Yard INT Return TD Bonus',
            90 : '50+ Yard Fumble Return TD Bonus',
            91 : 'Def 2-Point Return',
            92 : '',
            93 : '',
            94 : '',
            95 : '',
            96 : '',
            97 : '',
            98 : '',
            99 : '',
            100 : '',
            101 : '',
            102 : '',
            103 : '',
            104 : '',
            105 : '',
            106 : '',
            107 : '',
            108 : '',
            109 : '',
            110 : ''
            }

wayBack = [{'urlCode' : 20120829100111,
                'season' : 2012,
                'week' : 0},
               {'urlCode' : 20120925042919,
                'season' : 2012,
                'week' : 4},
               {'urlCode' : 20121013223321,
                'season' : 2012,
                'week' : 6},
               {'urlCode' : 20121017090252,
                'season' : 2012,
                'week' : 7},
               {'urlCode' : 20121025151812,
                'season' : 2012,
                'week' : 8},
               {'urlCode' : 20121125082042,
                'season' : 2012,
                'week' : 12},
               {'urlCode' : 20130826104546,
                'season' : 2013,
                'week' : 0},
               {'urlCode' : 20130906025726,
                'season' : 2013,
                'week' : 1},
               {'urlCode' : 20130916075358,
                'season' : 2013,
                'week' : 3},
               {'urlCode' : 20130927180026,
                'season' : 2013,
                'week' : 4},
               {'urlCode' : 20131026055922,
                'season' : 2013,
                'week' : 8},
               {'urlCode' : 20131126032548,
                'season' : 2013,
                'week' : 13},
               {'urlCode' : 20140813022239,
                'season' : 2014,
                'week' : 0},
               {'urlCode' : 20140901182032,
                'season' : 2014,
                'week' : 1},
               {'urlCode' : 20140920211352,
                'season' : 2014,
                'week' : 3},
               {'urlCode' : 20141001080947,
                'season' : 2014,
                'week' : 5},
               {'urlCode' : 20141011191912,
                'season' : 2014,
                'week' : 6},
               {'urlCode' : 20141021232139,
                'season' : 2014,
                'week' : 8},
               {'urlCode' : 20141102064755,
                'season' : 2014,
                'week' : 9},
               {'urlCode' : 20141219012952,
                'season' : 2014,
                'week' : 16},
           {'urlCode' : 20150831053928,
                'season' : 2015,
                'week' : 0},
               {'urlCode' : 20150909051040,
                'season' : 2015,
                'week' : 1},
               {'urlCode' : 20150917072153,
                'season' : 2015,
                'week' : 2},
               {'urlCode' : 20150926045018,
                'season' : 2015,
                'week' : 3},
               {'urlCode' : 20151001053417,
                'season' : 2015,
                'week' : 4},
               {'urlCode' : 20151007001412,
                'season' : 2015,
                'week' : 5},
               {'urlCode' : 20151013050921,
                'season' : 2015,
                'week' : 6},
               {'urlCode' : 20151020040704,
                'season' : 2015,
                'week' : 7},
               {'urlCode' : 20151027070024,
                'season' : 2015,
                'week' : 8},
               {'urlCode' : 20151104001505,
                'season' : 2015,
                'week' : 9},
               {'urlCode' : 20151112123546,
                'season' : 2015,
                'week' : 10},
               {'urlCode' : 20151120131045,
                'season' : 2015,
                'week' : 11},
               {'urlCode' : 20151128094358,
                'season' : 2015,
                'week' : 12},
               {'urlCode' : 20151206133252,
                'season' : 2015,
                'week' : 13},
               {'urlCode' : 20151209085708,
                'season' : 2015,
                'week' : 14},
               {'urlCode' : 20151214204635,
                'season' : 2015,
                'week' : 15},
               {'urlCode' : 20151222132006,
                'season' : 2015,
                'week' : 16},
               {'urlCode' : 20151230071532,
                'season' : 2015,
                'week' : 17},
               {'urlCode' : 20160826033611,
                'season' : 2016,
                'week' : 0},
               {'urlCode' : 20160907093916,
                'season' : 2016,
                'week' : 1},
               {'urlCode' : 20160913152613,
                'season' : 2016,
                'week' : 2},
               {'urlCode' : 20160919024758,
                'season' : 2016,
                'week' : 3},
               {'urlCode' : 20160930224419,
                'season' : 2016,
                'week' : 4},
               {'urlCode' : 20161008062915,
                'season' : 2016,
                'week' : 5},
               {'urlCode' : 20161015053344,
                'season' : 2016,
                'week' : 6},
               {'urlCode' : 20161024054034,
                'season' : 2016,
                'week' : 8},
               {'urlCode' : 20161102095347,
                'season' : 2016,
                'week' : 9},
               {'urlCode' : 20161115174109,
                'season' : 2016,
                'week' : 11},
               {'urlCode' : 20161128113237,
                'season' : 2016,
                'week' : 13},
               {'urlCode' : 20170828093539,
                'season' : 2017,
                'week' : 0},
               {'urlCode' : 20170908203952,
                'season' : 2017,
                'week' : 1},
               {'urlCode' : 20170913153409,
                'season' : 2017,
                'week' : 2},
               {'urlCode' : 20170920112609,
                'season' : 2017,
                'week' : 3},
               {'urlCode' : 20171003052159,
                'season' : 2017,
                'week' : 5},
               {'urlCode' : 20171014020746,
                'season' : 2017,
                'week' : 6},
               {'urlCode' : 20171028163704,
                'season' : 2017,
                'week' : 8},
               {'urlCode' : 20171114230909,
                'season' : 2017,
                'week' : 11},
               {'urlCode' : 20171212061249,
                'season' : 2017,
                'week' : 15}
        ]
